name: Access ID Workflow

on:
  push:
    branches:
      - main

jobs:
  print-access-id:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print ACCESS_ID
        env:
          ACCESS_ID: ${{ vars.ACCESS_ID }}
        run: echo "The ACCESS_ID is $ACCESS_ID"
